name: Clean docs branches
on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install python packages
        run: pip install mkdocs-material mkdoxy pillow cairosvg mkdocs-macros-plugin mike
      - name: Upgrade Jinja2
        run: pip install Jinja2 --upgrade
      - name: Print mkdocs version
        run: mkdocs --version
      - name: Make sure git user.name is configured because it is used by mike versioning tool.
        run: git config --global user.name "${{github.actor}}"
      - name: Make sure git user.email is configured
        run: git config --global user.email "${{github.actor}}@users.noreply.github.com" 
      - name: Clear all docs versions (do not uncomment except if you know what u'r doing)
        run: mike delete dev
