name: Clean docs branches
on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name from repository_dispatch event
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          branch_name="${{ github.event.client_payload.version }}"
          echo "Triggered by branch: $branch_name"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all commits/branches, fixes fast forward issue of mike tool
      - name: Install python packages
        run: pip install mkdocs-material mkdoxy pillow cairosvg mkdocs-macros-plugin mike
      - name: Upgrade Jinja2
        run: pip install Jinja2 --upgrade
      - name: Print mkdocs version
        run: mkdocs --version
      - name: Make sure git user.name is configured because it is used by mike versioning tool.
        run: git config --global user.name "${{github.actor}}"
      - name: Make sure git user.email is configured
        run: git config --global user.email "${{github.actor}}@users.noreply.github.com" 
      - name: List all docs current branches
        run: mike list
      - name: Set default branch
        run: mike set-default default
      - name: Clear all docs versions (do not uncomment except if you know what u'r doing)
        run: mike delete dev
