name: Manually publish docs for 1.0
on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all commits/branches, fixes fast forward issue of mike tool

      - name: Checkout OwnTech Core repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/Core
          ref: v1.0.0
          path: docs/core

      - name: Checkout OwnTech Bootloader repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/bootloader
          ref: docs
          path: docs/bootloader
          sparse-checkout: |
            docs/getting_started.md
            docs/images/*
          sparse-checkout-cone-mode: false

      - name: Checkout OwnTech Twist V1_4 repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/twist
          ref: TWIST-V1.4.X
          path: docs/twistV14
          sparse-checkout: |
            docs/getting_started.md
            docs/images/
            docs/images/*
          sparse-checkout-cone-mode: false

      - name: Debug Image Directory
        run: ls -R docs/twistV14/docs/images


      - name: Checkout OwnTech Twist V1_3 repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/twist
          ref: TWIST-V1.3
          path: docs/twistV13
          sparse-checkout: |
            docs/getting_started.md
          sparse-checkout-cone-mode: false

      - name: Checkout OwnTech Twist V1_2 repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/twist
          ref: TWIST-V1.2
          path: docs/twistV12
          sparse-checkout: |
            docs/getting_started.md
          sparse-checkout-cone-mode: false

      - name: Remove unecessary twist folder
        run: |
          mkdir docs/twist
          mkdir docs/twist/1.4.1
          mkdir docs/twist/1.4.1/images
          mkdir docs/twist/1.3.0
          mkdir docs/twist/1.2.0
          mv docs/twistV14/docs/getting_started.md docs/twist/1.4.1/getting_started.md
          mv docs/twistV14/docs/images/* docs/twist/1.4.1/images
          mv docs/twistV13/docs/getting_started.md docs/twist/1.3.0/getting_started.md
          mv docs/twistV12/docs/getting_started.md docs/twist/1.2.0/getting_started.md
          rm -rf docs/twistV14
          rm -rf docs/twistV13
          rm -rf docs/twistV12

      - name: Checkout OwnTech SPIN V1_2 repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/spin
          ref: SPIN-V1.2
          path: docs/spinV12
          sparse-checkout: |
            docs/getting_started.md
          sparse-checkout-cone-mode: false

      - name: Checkout OwnTech SPIN V1_1 repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/spin
          ref: SPIN-V1.1
          path: docs/spinV11
          sparse-checkout: |
            docs/getting_started.md
          sparse-checkout-cone-mode: false

      - name: Checkout OwnTech SPIN V1_0 repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/spin
          ref: SPIN-V1.0
          path: docs/spinV10
          sparse-checkout: |
            docs/getting_started.md
          sparse-checkout-cone-mode: false

      - name: Remove unecessary spin folder
        run: |
          mkdir docs/spin
          mkdir docs/spin/1.2.0
          mkdir docs/spin/1.1.0
          mkdir docs/spin/1.0.0
          mv docs/spinV12/docs/getting_started.md docs/spin/1.2.0/getting_started.md
          mv docs/spinV11/docs/getting_started.md docs/spin/1.1.0/getting_started.md
          mv docs/spinV10/docs/getting_started.md docs/spin/1.0.0/getting_started.md
          rm -rf docs/spinV12
          rm -rf docs/spinV11
          rm -rf docs/spinV10

      - name: Checkout OwnTech OWNVERTER repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/ownverter
          ref: dev
          path: docs/ownverterV10
          sparse-checkout: |
            docs/getting_started.md
            docs/images/
            docs/images/*
          sparse-checkout-cone-mode: false

      - name: Remove unecessary ownverter folder
        run: |
          mkdir docs/ownverter
          mkdir docs/ownverter/1.0.0
          mkdir docs/ownverter/1.0.0/images/
          mv docs/ownverterV10/docs/getting_started.md docs/ownverter/1.0.0/getting_started.md
          mv docs/ownverterV10/docs/images/* docs/ownverter/1.0.0/images
          rm -rf docs/ownverterV10

      - name: Checkout OwnTech Control library repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/control_library
          ref: docs
          path: docs/controlLibrary

      - name: Checkout OwnTech Examples repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/examples
          ref: docs
          path: docs/examples

      - name: Checkout OwnTech Matlab repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/Owntech-Matlab
          path: docs/Matlab
          sparse-checkout: |
            docs

      - name: Checkout OwnTech OwnModels repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/OwnModels
          path: docs/OwnModels
          sparse-checkout: |
            docs

      - name: Checkout OwnTech OwnPlot repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/OwnPlot
          ref: doc_v1.6.0_2
          path: docs/OwnPlot
          sparse-checkout: |
            docs

      - uses: ssciwr/doxygen-install@v1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install python packages
        run: pip install mkdocs-material mkdoxy pillow cairosvg mkdocs-macros-plugin mkdocs-drawio mike
      - name: Upgrade Jinja2
        run: pip install Jinja2 --upgrade

      - name: Configure navigation menu for version 1.0
        run: |
          rm $GITHUB_WORKSPACE/mkdocs.yml
          cp $GITHUB_WORKSPACE/version-specific-yaml/mkdocs_1.0.yml $GITHUB_WORKSPACE/mkdocs.yml

      - name: Print mkdocs version
        run: mkdocs --version
      - name: Make sure git user.name is configured because it is used by mike versioning tool.
        run: git config --global user.name "${{github.actor}}"
      - name: Make sure git user.email is configured
        run: git config --global user.email "${{github.actor}}@users.noreply.github.com" 
      - name: Publish docs for v1.0.0 using mike versioning tool
        run: mike deploy --push --update-aliases 1.0.0 latest

